// Generated by scripts/export_landing_config.py; public values only.
window.LANDING_CONFIG = {
  "counterId": 113108225,
  "clickGoal": "telegram_click",
  "apiUrl": "https://api.my-telegram-org-error.nuvqetra.com/v1/visits",
  "botUrl": "https://t.me/my_telegram_org_error_bot"
};
